name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Запуск тестов
      - name: Run tests
        run: |
          pytest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
          QWEN_API_URL: ${{ secrets.QWEN_API_URL }}
          QWEN_MODEL: ${{ secrets.QWEN_MODEL }}

      # Шаг 5: Подключение к серверу и обновление кода
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/fishventure-api-service
            
            # Создание виртуального окружения
            python3 -m venv venv
            source venv/bin/activate
          
            # Проверка наличия локальных изменений
            if [[ -n $(git status --porcelain) ]]; then
              git stash push -m "Сохранение локальных изменений перед обновлением"
            fi
            
            # Обновление кода из GitHub
            git pull origin master
            
            # Применение локальных изменений
            git stash pop || true
            
            # Разрешение конфликтов (если есть)
            if git diff --name-only --diff-filter=U | grep -q .; then
              echo "Разрешение конфликтов..."
              git add .
              git commit -m "Resolved merge conflicts after stash pop"
            fi
            
            # Установка зависимостей
            pip install -r requirements.txt
            
            # Применение миграций базы данных (если есть)
            alembic upgrade head
            
            # Перезапуск сервера
            sudo systemctl restart your_service_name